name: aiven-terraform-provider-demo
run-name: Apply terraform config and create Aiven resources
on: [push]
#  workflow_dispatch:
#      inputs:
#          branch:
#            description: 'Define branch name'     
#            required: true
#            default: 'branch'
env:
  TF_VAR_aiven_api_token: "${{ secrets.AIVEN_TOKEN }}"
jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    # runs-on: runs-on: [self-hosted, akte]
    steps:
    - uses: sturlabragason/terraform_state_artifact@v3
      with:
        encryptionkey: ${{ secrets.encryptionkey }}
          
    
