name: aiven-terraform-provider-demo
run-name: Apply terraform config and create Aiven resources
on: [push]
env:
  TF_VAR_aiven_api_token: "${{ secrets.AIVEN_TOKEN }}"
jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: sturlabragason/terraform_state_artifact@v2
      with:
          encryptionkey: ${{ secrets.encryptionkey }}
          
    
