name: aiven-terraform-provider-demo
run-name: Apply terraform config and create Aiven resources
on: [push]
jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - id: plan
        run: terraform plan -no-color
        env:
          TF_VAR_aiven_api_token: "${{ secrets.AIVEN_TOKEN }}"
      - id: apply
        run: terraform apply -auto-approve -input=false
        env:
          TF_VAR_aiven_api_token: "${{ secrets.AIVEN_TOKEN }}"   

